description: PS/2 mouse configuration

compatible: "zmk,input-mouse-ps2"

include: base.yaml

properties:
  ps2-device:
    type: phandle
    required: true
    description: The ps2 device the mouse should use.

  rst-gpios:
    type: phandle-array
    required: false
    description: GPIO for Power-On-Reset.

  sampling-rate:
    type: int
    description: Allowed values are 10, 20, 40, 60, 80, 100, 200.
    enum: [10, 20, 40, 60, 80, 100, 200]

  scroll-mode:
    type: boolean
  
  disable-clicking:
    type: boolean

  tp-press-to-select:
    type: boolean

  tp-press-to-select-threshold:
    type: int

  tp-sensitivity:
    type: int

  tp-neg-inertia:
    type: int

  tp-val6-upper-speed:
    type: int

  tp-x-invert:
    type: boolean

  tp-y-invert:
    type: boolean

  tp-xy-swap:
    type: boolean

  layer-toggle:
    type: int
    required: false