manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # This project provides the PS/2 hardware driver
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: infused-kim
      revision: main
    # This project provides the 'input-listener' and 'input-processors' logic
    - name: zmk-input-behavior-listener
      remote: infused-kim
      revision: main
  self:
    path: config