# Copyright (c) 2023 GitHub Copilot
# SPDX-License-Identifier: Apache-2.0

description: RP2040 PIO PS/2 driver

compatible: "pio-ps2"

include: base.yaml

properties:
    scl-gpios:
      type: phandle-array
      required: true
      description: GPIO to which the SCL (Clock) pin is connected.
    sda-gpios:
      type: phandle-array
      required: true
      description: GPIO to which the SDA (Data) pin is connected.
